development:
  adapter: postgresql
  encoding: unicode
  database: ogyz_development
  pool: 5
  username: postgres
  password: postgres
  host: postgres
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: ogyz_test
  pool: 5
  username: postgres
  password: postgres
  host: postgres
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: ogyz_production
  pool: 5
  username: postgres
  password: postgres
  host: postgres
  port: 5432